services:
  ### ["create_service_telegraf_on_master", "max_voltage"],
  telegraf_max_voltage:
    environment:
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}

  ### ["create_service_telegraf_on_master", "temperature"],
  telegraf_temperature:
    environment:
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}
