services:
  nats_monitor:
    image: logimethods/int_monitor:1.0
    environment:
      - WAIT_FOR=${NATS_NAME}
      - NATS_NAME=${NATS_NAME}
      - EUREKA_DEBUG=true
      - NATS_SUBJECT=${NATS_CLIENT_SUBJECT}
    command: /main
