services:
  ### create_service_app_streaming,
  # TODO: Check
  app_streaming:
    image: logimethods/smart-meter:app-streaming${postfix}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    environment:
      - DEPENDS_ON=${NATS_NAME},${CASSANDRA_MAIN_NAME}
#      - NATS_URI=${NATS_URI}
      - NATS_NAME=${NATS_NAME}
      - SPARK_MASTER_URL=${SPARK_MASTER_URL_STREAMING}
      - STREAMING_DURATION=${STREAMING_DURATION}
      - CASSANDRA_URL=${CASSANDRA_MAIN_NAME}
      - LOG_LEVEL=${APP_STREAMING_LOG_LEVEL}
      - TARGETS=${APP_STREAMING_TARGETS}
      - SPARK_CORES_MAX=${APP_STREAMING_SPARK_CORES_MAX}
    command: com.logimethods.nats.connector.spark.app.SparkMaxProcessor "smartmeter.voltage.raw" "smartmeter.voltage.extract.max" "Smartmeter MAX Streaming"
