services:
  ### create_service_app_streaming,
  nats_monitor:
    environment:
      - NATS_USERNAME_FILE=/run/secrets/nats_username_secret
      - NATS_PASSWORD_FILE=/run/secrets/nats_password_secret
    secrets:
      - nats_username_secret
      - nats_password_secret