services:
  ### create_service_inject
  inject:
    environment:
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}

  ### create_service_cassandra_inject,
  cassandra_inject:
    environment:
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}
