services:
  ### create_service_nats,
  nats:
    deploy:
      placement:
        constraints:
          - node.role == ${MASTER_NODE}
    command: /gnatsd -c gnatsd-${CLUSTER_MODE}.conf -m 8222 ${NATS_DEBUG} -cluster nats://0.0.0.0:6222

  nats_cluster:
    image: ((docker-dz_nats-server-repository)):((docker-dz_nats-server-tag))((docker-additional-tag))
    deploy:
      mode: global
      placement:
        constraints:
          - node.role != ${MASTER_NODE}
#      update_config:
#        parallelism: 1
#        delay: 10s
    environment:
      - READY_WHEN=\"Server is ready\"
      - NATS_NAME=${NATS_NAME}
    volumes:
      - "/proc:/writable-proc"
    command: /gnatsd -c gnatsd-${CLUSTER_MODE}.conf -m 8222 ${NATS_DEBUG} -cluster nats://0.0.0.0:6222 -routes nats://nats:6222
