services:
  ### TODO: ["create_volume", "cassandra"],
  ### create_service_cassandra,
  cassandra_cluster_main:
    image: ((docker-dz_cassandra-repository)):((docker-dz_cassandra-tag))((docker-additional-tag))
    deploy:
      placement:
        constraints:
          - node.role == ${MASTER_NODE}
    environment:
#      - LOCAL_JMX=no
      - CASSANDRA_SETUP_FILE=${CASSANDRA_SETUP_FILE}
      - CASSANDRA_COUNT_PORT=${CASSANDRA_COUNT_PORT}
    ports:
      - "${CASSANDRA_COUNT_PORT}:6161"
