services:
  ### create_service_spark_master,
  zeppelin:
    image: ${zeppelin_image}:${zeppelin_tag}
    deploy:
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
    environment:
      - ZEPPELIN_LOG_DIR=${ZEPPELIN_LOG_DIR}
      - ZEPPELIN_NOTEBOOK_DIR=${ZEPPELIN_NOTEBOOK_DIR}
    ports:
      - "${ZEPPELIN_WEB_PORT}:8080"
    volumes:
      - "${zeppelin_logs_volume}:/logs"
      - "${zeppelin_notebook_volume}:/notebook"

# https://docs.docker.com/compose/compose-file/#volume-configuration-reference
volumes:
  zeppelin_logs:
    name: "${zeppelin_logs_volume}"
  zeppelin_notebook:
    name: "${zeppelin_notebook_volume}"
