services:
  ### create_service_spark_master,
  zeppelin:
    image: ${zeppelin_image}:${zeppelin_tag}
    deploy:
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
    environment:
      - ZEPPELIN_LOG_DIR=${ZEPPELIN_LOG_DIR}
      - ZEPPELIN_NOTEBOOK_DIR=${ZEPPELIN_NOTEBOOK_DIR}
    ports:
      - "${ZEPPELIN_UI_PORT}:8080"
    volumes:
      - "${logs_dir}:/logs"
      - "${notebook_dir}:/notebook"