services:
  ### create_service_nats,
  nats:
    environment:
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}
      - NATS_CLUSTER_USERNAME=/${NATS_CLUSTER_USERNAME}
      - NATS_CLUSTER_PASSWORD=${NATS_CLUSTER_PASSWORD}

  nats_cluster:
    environment:
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}
      - NATS_CLUSTER_USERNAME=/${NATS_CLUSTER_USERNAME}
      - NATS_CLUSTER_PASSWORD=${NATS_CLUSTER_PASSWORD}

  ## For TESTING/DEBUG ONLY! ##
  nats_client:
    environment:
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}
