services:
  nats_cluster:
    environment:
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}
      - NATS_CLUSTER_USERNAME=${NATS_CLUSTER_USERNAME}
      - NATS_CLUSTER_PASSWORD=${NATS_CLUSTER_PASSWORD}