services:
services:
  ### TODO: ["create_volume", "cassandra"],
  ### create_service_cassandra,
  cassandra-cluster-main:
    deploy:
      placement:
        constraints:
          - node.role == ${MASTER_NODE}

  ### TODO: ["create_volume", "cassandra"],
  ### create_service_cassandra,
  cassandra-cluster-node:
    image: ((docker-dz_cassandra-repository)):((docker-dz_cassandra-tag))((docker-additional-tag))
    deploy:
      mode: global
      placement:
        constraints:
          - node.role != ${MASTER_NODE}
    environment:
#      - LOCAL_JMX=no
      - READY_WHEN=""
#      - FAILED_WHEN=\"CASSANDRA_SEEDS:\\n\"
      - DEPENDS_ON=${EUREKA_NAME},${CASSANDRA_MAIN_NAME}
      - SETUP_LOCAL_CONTAINERS=true
      - PROVIDED_CASSANDRA_SEEDS=$${${CASSANDRA_MAIN_NAME}_local}
#      - EUREKA_DEBUG=true
#      - CHECK_DEPENDENCIES_INTERVAL=20
      - PING_ALLOWED=false