version: "3.1"

### create_network,
#### docker ${remote} network create --driver overlay --attachable ${NETWORK_NAME}
networks:
  default:
    external:
      name: ${NETWORK_NAME}

services:
  ### ["create_service", "eureka", 1],
  eureka:
    image: logimethods/eureka:${eureka_version}
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "${FLASK_PORT}:5000"
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  ### create_service_nats,
  nats:
    image: ((docker-dz_nats-server-repository)):((docker-dz_nats-server-tag))((docker-additional-tag))
#    deploy:
#      update_config:
#        parallelism: 1
#        delay: 10s
    environment:
      - READY_WHEN=\"Server is ready\"
      - NATS_NAME=${NATS_NAME}
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - "/proc:/writable-proc"

  ## For TESTING/DEBUG ONLY! ##
  nats_client:
    image: ((docker-dz_nats-client-repository)):((docker-dz_nats-client-tag))((docker-additional-tag))
    environment:
      - WAIT_FOR=${NATS_NAME}
      - NATS_NAME=${NATS_NAME}
      - EUREKA_DEBUG=true
      - NATS_SUBJECT=${NATS_CLIENT_SUBJECT}
    command: /main
