services:
  ### create_service_nats,
  nats:
    environment:
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}
      - NATS_CLUSTER_USERNAME=${NATS_CLUSTER_USERNAME}
      - NATS_CLUSTER_PASSWORD=${NATS_CLUSTER_PASSWORD}
