services:
  ### ["create_service_telegraf_on_master", "docker"],
  telegraf_docker:
    image: logimethods/smart-meter:telegraf${postfix}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    environment:
      - SETUP_LOCAL_CONTAINERS=true
      - EUREKA_URL=${EUREKA_NAME}
      - NODE_ID={{.Node.ID}}
      - SERVICE_ID={{.Service.ID}}
      - SERVICE_NAME={{.Service.Name}}
      - SERVICE_LABELS={{.Service.Labels}}
      - TASK_ID={{.Task.ID}}
      - TASK_NAME={{.Task.Name}}
      - TASK_SLOT={{.Task.Slot}}
      - JMX_PASSWORD=$JMX_PASSWORD
      - TELEGRAF_DEBUG=$TELEGRAF_DEBUG
      - TELEGRAF_QUIET=$TELEGRAF_QUIET
      - TELEGRAF_INTERVAL=$TELEGRAF_INTERVAL
      - TELEGRAF_INPUT_TIMEOUT=$TELEGRAF_INPUT_TIMEOUT
      # Specific
      - PING_ALLOWED=false
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: telegraf --output-filter ${TELEGRAF_OUTPUT_FILTER} -config /etc/telegraf/docker.conf

  ### ["create_service", "prometheus_nats_exporter", 1],
  prometheus_nats_exporter:
    image: ${prometheus_nats_exporter_image}:${prometheus_nats_exporter_tag}${postfix}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    command: ${PROMETHEUS_NATS_EXPORTER_FLAGS} ${PROMETHEUS_NATS_EXPORTER_DEBUG} ${PROMETHEUS_NATS_EXPORTER_URLS}
