services:
  ### run_metrics,
  #### run_metrics_graphite
  metrics:
    image: hopsoft/graphite-statsd:${graphite_statsd_tag}
    ports:
      - "81:80"
  #### run_metrics_prometheus
  prometheus:
    image: logimethods/smart-meter:prometheus${postfix}
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "9090:9090"
    command: -storage.local.path=/data -config.file=/etc/prometheus/prometheus.yml
  #### create_service_influxdb
  influxdb:
    image: influxdb
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "8083:8083"
      - "8086:8086"
      - "2003:2003"
  #### run_metrics_grafana
  grafana:
    image: grafana/grafana:${grafana_tag}
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "${METRICS_GRAFANA_WEB_PORT}:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - "grafana-volume:/var/lib/grafana"

volumes:
  grafana-volume:
    external: true
