###### JOBS #######

jobs:
- name: build-docker-dz_templater
  public: true
  serial: true
  plan:
  - get: github-repo-dz_templater
    trigger: true
  - put: docker-dz_templater
    params:
      build: github-repo-dz_templater((github-dz_templater-dockerfile-path))

- name: build-docker-dz_compose
  public: true
  serial: true
  plan:
  - get: github-repo-dz_compose
    trigger: true
  - get: docker-dz_templater
    trigger: true
  - task: add_properties
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ((docker-dz_templater-repository))
          tag: ((docker-dz_templater-tag))((docker-additional-tag))
      inputs:
      - name: github-repo-dz_compose
      outputs:
      - name: added_properties
      run:
        path: sh
        args:
        - -exc
        - |
          mkdir added_properties/compose/
          cp -R github-repo-dz_compose/compose/* added_properties/compose/
          cp github-repo-dz_compose/concourse/properties.yml added_properties/compose/
          ./set_properties_to_templates.sh added_properties
  - put: docker-dz_compose
    params:
      build: added_properties((github-dz_compose-dockerfile-path))

###### RESOURCES ######

resources:
- name: github-repo-dz_templater
  type: git
  source:
    uri: ((github-uri))
    branch: ((github-branch))
    paths:
      - dz_templater/**
    git_user: ((github-username))
    private_key: ((github-private-key))

- name: github-repo-dz_compose
  type: git
  source:
    uri: ((github-uri))
    branch: ((github-branch))
    paths:
      - dz_compose/**
    git_user: ((github-username))
    private_key: ((github-private-key))

## Deetazilla Docker Images ##

- name: docker-dz_templater
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-dz_templater-repository))
    tag: ((docker-dz_templater-tag))((docker-additional-tag))

- name: docker-dz_compose
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-dz_compose-repository))
    tag: ((docker-dz_compose-tag))((docker-additional-tag))


