###### JOBS #######

jobs:
- name: build-docker-compose
  public: true
  serial: true
  plan:
  - get: github-repo-compose
    trigger: true
  - put: docker-compose
    params:
      build: github-repo-compose((github-compose-dockerfile-path))

- name: build-docker-eureka
  public: true
  serial: true
  plan:
  - get: github-repo
    trigger: true
  - task: complete_dockerfiles
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: "latest"
      inputs:
      - name: github-repo
      outputs:
      - name: complete_dockerfiles
      run:
        path: sh
        args:
        - -exc
        - |
          cp -R github-repo/* complete_dockerfiles/
          cd complete_dockerfiles/
          ./set_properties_to_ek_templates.sh
  - put: docker-ek_cassandra
    params:
      build: complete_dockerfiles((docker-ek_cassandra-dockerfile-path))
  - put: docker-ek_nats-client
    params:
      build: complete_dockerfiles((docker-ek_nats-client-dockerfile-path))
  - put: docker-ek_nats-server
    params:
      build: complete_dockerfiles((docker-ek_nats-server-dockerfile-path))
  - put: docker-ek_telegraf
    params:
      build: complete_dockerfiles((docker-ek_telegraf-dockerfile-path))

- name: build-docker-int_inject
  public: true
  serial: true
  plan:
  - get: github-repo-int_inject
    trigger: true
  - task: set-up_dockerfile_inject
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: hseeberger/scala-sbt
          tag: "latest"
      inputs:
      - name: github-repo-int_inject
      outputs:
      - name: dockerfile_integration
      run:
        path: bash
        args:
        - -exc
        - |
          echo "---------------------- INJECT ----------------------"
          pushd github-repo-int_inject/integration/docker_inject/
          echo "q" | sbt --info clean assembly dockerFileTask
          pushd target/docker
          mv Dockerfile Dockerfile_middle
          cp ../../entrypoint_insert.sh .
          cat ../../Dockerfile_pre Dockerfile_middle ../../Dockerfile_post >> Dockerfile
          popd
          rm -Rf ./docker
          mv target/docker .
          popd
          echo "---------------------- FINAL COPY ----------------------"
          cp -R github-repo-int_inject/integration/* dockerfile_integration/
          # ls -als dockerfile_integration/*/*
  - put: docker-int_inject
    params:
      build: dockerfile_integration((docker-int_inject-dockerfile-path))

- name: build-docker-int_streaming
  public: true
  serial: true
  plan:
  - get: github-repo-int_streaming
    trigger: true
  - task: set-up_dockerfile_inject
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: hseeberger/scala-sbt
          tag: "latest"
      inputs:
      - name: github-repo-int_streaming
      outputs:
      - name: dockerfile_integration
      run:
        path: bash
        args:
        - -exc
        - |
          echo "---------------------- STREAMING ----------------------"
          pushd github-repo-int_streaming/integration/docker_streaming/
          echo "q" | sbt --info clean assembly dockerFileTask
          pushd target/docker
          mv Dockerfile Dockerfile_middle
          cp ../../entrypoint_insert.sh .
          cat ../../Dockerfile_pre Dockerfile_middle ../../Dockerfile_post >> Dockerfile
          popd
          rm -Rf ./docker
          mv target/docker .
          popd
          echo "---------------------- FINAL COPY ----------------------"
          cp -R github-repo-int_streaming/integration/* dockerfile_integration/
          # ls -als dockerfile_integration/*/*
  - put: docker-int_streaming
    params:
      build: dockerfile_integration((docker-int_streaming-dockerfile-path))

- name: build-docker-int_monitor
  public: true
  serial: true
  plan:
  - get: github-repo-int_monitor
    trigger: true
  - task: set-up_dockerfile_inject
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: hseeberger/scala-sbt
          tag: "latest"
      inputs:
      - name: github-repo-int_monitor
      outputs:
      - name: dockerfile_integration
      run:
        path: bash
        args:
        - -exc
        - |
          echo "---------------------- MONITOR ----------------------"
          pushd github-repo-int_monitor/integration/docker_monitor/
          echo "q" | sbt --info clean assembly dockerFileTask
          rm -Rf ./docker
          mv target/docker .
          popd
          echo "---------------------- FINAL COPY ----------------------"
          cp -R github-repo-int_monitor/integration/* dockerfile_integration/
          # ls -als dockerfile_integration/*/*
  - put: docker-int_monitor
    params:
      build: dockerfile_integration((docker-int_monitor-dockerfile-path))

- name: build-docker-int_compose
  public: true
  serial: true
  plan:
  - get: github-repo-int_compose
    trigger: true
  - put: docker-int_compose
    params:
      build: github-repo-int_compose((github-int_compose-dockerfile-path))

###### RESOURCES ######

resources:
- name: github-repo
  type: git
  source:
    uri: ((github-uri))
    branch: master
    ignore_paths:
      - integration/**
      - compose/**
      - concourse/**
      - README.md
    git_user: ((github-username))
    private_key: ((github-private-key))

- name: github-repo-int_inject
  type: git
  source:
    uri: ((github-uri))
    branch: master
    paths:
      - integration/docker_inject/**
    git_user: ((github-username))
    private_key: ((github-private-key))

- name: github-repo-int_streaming
  type: git
  source:
    uri: ((github-uri))
    branch: master
    paths:
      - integration/docker_streaming/**
    git_user: ((github-username))
    private_key: ((github-private-key))

- name: github-repo-int_monitor
  type: git
  source:
    uri: ((github-uri))
    branch: master
    paths:
      - integration/docker_monitor/**
    git_user: ((github-username))
    private_key: ((github-private-key))

- name: github-repo-int_compose
  type: git
  source:
    uri: ((github-uri))
    branch: master
    paths:
      - integration/compose/**
    git_user: ((github-username))
    private_key: ((github-private-key))

- name: github-repo-compose
  type: git
  source:
    uri: ((github-uri))
    branch: master
    paths:
      - compose/**
    git_user: ((github-username))
    private_key: ((github-private-key))

## Eureka Docker Images ##

- name: docker-compose
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-compose-repository))

- name: docker-ek_cassandra
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-ek_cassandra-repository))
    tag: ((docker-ek_cassandra-tag))

- name: docker-ek_nats-client
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-ek_nats-client-repository))
    tag: ((docker-ek_nats-client-tag))

- name: docker-ek_nats-server
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-ek_nats-server-repository))
    tag: ((docker-ek_nats-server-tag))

- name: docker-ek_telegraf
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-ek_telegraf-repository))
    tag: ((docker-ek_telegraf-tag))

## Integration Docker Images ##

- name: docker-int_compose
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-int_compose-repository))

- name: docker-int_inject
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-int_inject-repository))
    tag: ((docker-int_inject-tag))

- name: docker-int_streaming
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-int_streaming-repository))
    tag: ((docker-int_streaming-tag))

- name: docker-int_monitor
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-int_monitor-repository))
    tag: ((docker-int_monitor-tag))

