###### JOBS #######

jobs:
- name: build-docker-compose
  public: true
  serial: true
  plan:
  - get: github-repo
    trigger: true
  - put: docker-compose
    params:
      build: github-repo((github-compose-dockerfile-path))

- name: build-docker-eureka
  public: true
  serial: true
  plan:
  - get: github-repo
    trigger: true
  - task: complete_dockerfiles
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: "latest"
      inputs:
      - name: github-repo
      outputs:
      - name: complete_dockerfiles
      run:
        path: sh
        args:
        - -exc
        - |
          cp -R github-repo/* complete_dockerfiles/
          cd complete_dockerfiles/
          ./set_properties_to_ek_templates.sh
  - put: docker-ek_cassandra
    params:
      build: complete_dockerfiles((docker-ek_cassandra-dockerfile-path))
  - put: docker-ek_nats-client
    params:
      build: complete_dockerfiles((docker-ek_nats-client-dockerfile-path))
  - put: docker-ek_nats-server
    params:
      build: complete_dockerfiles((docker-ek_nats-server-dockerfile-path))
  - put: docker-ek_telegraf
    params:
      build: complete_dockerfiles((docker-ek_telegraf-dockerfile-path))


- name: build-docker-integration
  public: true
  serial: true
  plan:
  - get: github-repo
    trigger: true
  - task: set-up_dockerfile_inject
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: hseeberger/scala-sbt
          tag: "latest"
      inputs:
      - name: github-repo
      outputs:
      - name: dockerfile_inject
      run:
        path: bash
        args:
        - -exc
        - |
          pushd github-repo/integration/docker_inject/
          sbt --info clean assembly dockerFileTask
          pushd target/docker
          mv Dockerfile Dockerfile_middle
          cp ../../entrypoint_insert.sh .
          cat ../../Dockerfile_pre Dockerfile_middle ../../Dockerfile_post >> Dockerfile
          popd
          rm -Rf ./docker
          mv target/docker .
          popd
#          ls -als github-repo/integration/*/*
#          echo "---------"
          cp -R github-repo/integration/* dockerfile_inject/
#          ls -als dockerfile_inject/*/*
  - put: docker-int_inject
    params:
      build: dockerfile_inject((docker-int_inject-dockerfile-path))


###### RESOURCES ######

resources:
- name: github-repo
  type: git
  source:
    uri: ((github-uri))
    branch: master
    git_user: ((github-username))
    private_key: ((github-private-key))

- name: docker-compose
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-compose-repository))

## Eureka Docker Images ##

- name: docker-ek_cassandra
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-ek_cassandra-repository))
    tag: ((docker-ek_cassandra-tag))

- name: docker-ek_nats-client
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-ek_nats-client-repository))
    tag: ((docker-ek_nats-client-tag))

- name: docker-ek_nats-server
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-ek_nats-server-repository))
    tag: ((docker-ek_nats-server-tag))

- name: docker-ek_telegraf
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-ek_telegraf-repository))
    tag: ((docker-ek_telegraf-tag))

## Integration Docker Images ##

- name: docker-int_inject
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-int_inject-repository))
    tag: ((docker-int_inject-tag))

