services:
  nats_monitor:
    image: ((docker-int_monitor-repository)):((docker-int_monitor-tag))((docker-additional-tag))
    environment:
      - WAIT_FOR=${NATS_NAME}
      - EUREKA_DEBUG=true
#-      - NATS_NAME=${NATS_NAME}
#-      - NATS_SUBJECT=${NATS_CLIENT_SUBJECT}
    command: ${MONITOR_MAIN_CLASS} ${MONITOR_SUBJECT_INPUT}
