services:
  ### ["create_service_telegraf_on_master", "max_voltage"],
  telegraf_max_voltage:
    environment:
      - NATS_USERNAME_FILE=/run/secrets/nats_username_secret
      - NATS_PASSWORD_FILE=/run/secrets/nats_password_secret
    secrets:
      - nats_username_secret
      - nats_password_secret

  ### ["create_service_telegraf_on_master", "temperature"],
  telegraf_temperature:
    environment:
      - NATS_USERNAME_FILE=/run/secrets/nats_username_secret
      - NATS_PASSWORD_FILE=/run/secrets/nats_password_secret
    secrets:
      - nats_username_secret
      - nats_password_secret
